executors:
  latest-machine:
    machine:
      image: ubuntu-2404:current
jobs:
  build:
    environment:
      BUILDX_NO_DEFAULT_LOAD: 1
    executor: latest-machine
    steps:
      - checkout
      - run:
          command: make install-lint
          name: Install linters
      - run:
          command: make lint
          name: Lint code
      - run:
          command: make install
          name: Install binfmt Platforms
      - run:
          command: make build
          name: Build
  deploy:
    executor: latest-machine
    steps:
      - checkout
      - run:
          command: make install-lint
          name: Install linters
      - run:
          command: make lint
          name: Lint code
      - run:
          command: docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
          name: Login to Docker Hub
      - run:
          command: make install
          name: Install binfmt Platforms
      - run:
          command: make deploy
          name: Build & Push
version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - /.*-ci/
      - deploy:
          filters:
            branches:
              only:
                - main
  version: 2.1
